### ISSUE TITLE
draft-ietf-dnsop-zoneversion

### ISSUE THREAD

**Issue by moonshiner** [wkumari/Temp-DNSOP_Doc_Tracker#12] opened 2024-04-24 14:06 UTC
## Link: 

https://datatracker.ietf.org/doc/draft-ietf-dnsop-zoneversion/

## Authors:
*  H. Salgado
* M. Vergara
* D Wessels

## Related drafts

We need a Followup WGLC

**Comment by wkumari** [comment] 2024-05-08 14:27
Second, short WGLC started: https://mailarchive.ietf.org/arch/msg/dnsop/kpKU7P5Gxsmw-3qPJmMix-TdzO4/

**Comment by moonshiner** [comment] 2024-05-24 21:37
Updated the shepherds write up and re-submitted.

**Comment by wkumari** [comment] 2024-05-26 17:41
You say:
"Working Group Summary:
WG worked and collaborated on resolving any and all issues. No rough consensus."

This is ambiguous — "No rough consensus" could be understood to mean that there is no consensus, rough or otherwise. Yes, it should be clear what was intended, but I'm *sure* that some set of ADs will question this, so…


Please also add names for the document shepherd and responsible AD...

**Comment by moonshiner** [comment] 2024-05-28 14:54
I fixed this up with apologies.  I went through it another time looking for issues.

**Comment by wkumari** [comment] 2024-05-28 17:16
Ta, and no worries!

**Comment by wkumari** [comment] 2024-05-29 13:51
IETF LC started

**Comment by moonshiner** [comment] 2024-06-30 02:19
Revised ID needed.

**Comment by wkumari** [comment] 2024-08-23 22:24
RFC Editor state: EDIT

**Comment by moonshiner** [comment] 2024-09-21 18:15
RFC 9660 - AUTH48

**Closed as completed** 2024-11-01 21:59 UTC
Labels: 4: Maint, DONE!!!!!!
